#! /bin/sh

###Launch picom
picom --experimental-backends &

###Gaps and border settings
export gap=16
export monitor_gap=-4
#for gap=8 and monitor_gap=-6 the distance of windows from monitor borders will be 2px
#at least 1px must be left for xfce4-panel to work properly + the fixup at the bottom
bspc config border_width 3

###Desktop/workspace and monitor settings
export desktop_num=18
#This command will list all available monitor outputs
#xrandr -q | awk  '/D./ { print $1 }' 
#change commands below to fit proper names if needed
bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-A-0 -d 10 11 12 13 14 15 16 17 18


bspc config window_gap $gap
bspc config top_padding $monitor_gap
bspc config left_padding $monitor_gap
bspc config right_padding $monitor_gap
bspc config bottom_padding $monitor_gap

###Monocle mode settings
bspc config gapless_monocle  true
bspc config borderless_monocle  true
bspc config single_monocle true

###Monitor managing
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

###Various settings
bspc config presel_feedback true
bspc config automatic_scheme spiral
bspc config removal_adjustment true
bspc config directional_focus_tightness low
bspc config ignore_ewmh_focus false
bspc config ignore_ewmh_struts false
bspc config initial_polarity first_child

###Mouse controls
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

###Honor size hints: do not make windows smaller than they wish to be
bspc config honor_size_hints true 

###Theming settings
bspc config focused_border_color "#0598DB"
bspc config normal_border_color "#222D32"
bspc config presel_feedback_color "#003175"
bspc config active_border_color             "#0055CC"
bspc config urgent_border_color             "#F62427"
#bspc config presel_feedback_color           "$yellow"
#bspc config focused_locked_border_color     "$brightred"
#bspc config active_locked_border_color      "$red"
#bspc config normal_locked_border_color      "$black"
#bspc config focused_sticky_border_color     "$brightcyan"
#bspc config active_sticky_border_color      "$cyan"
#bspc config normal_sticky_border_color      "$black"
#bspc config focused_private_border_color    "$brightblue"
#bspc config active_private_border_color     "$blue"
#bspc config normal_private_border_color     "$black"


###Pointer and Focus
bspc config focus_follows_pointer true
#Some keybindings automatically enable and disable this setting
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor false

###Settings for manual splitting
bspc config split_ratio         0.5



###Rules for window managing and positioning
bspc rule --add  "Wrapper-2.0" manage=on layer=above state=floating private=on border=off #This one is responsible for Whiskermenu
bspc rule --add  Orage state=floating private=on
bspc rule --add  albert layer=above state=floating center=on border=off focus=on follow=on marked=on
bspc rule --add  "Xfce4-panel" layer=above border=off manage=off state=floating private=on locked=on
bspc rule --add  "Xfce4-panel:Panel Preferences" state=floating
bspc rule --add  screenkey --unmanage
bspc rule --add  Pidgin state=floating private=on
bspc rule --add  Ncmpcpp state=pseudo_tiled
bspc rule --add  Cava state=floating private=on
bspc rule --add  gcolor2 state=floating center=on
bspc rule --add  Gpick state=floating
bspc rule --add  lxappearance state=floating center=on
bspc rule --add  gmrun state=floating center=on
bspc rule --add  lxterminal state=floating center=on sticky=on
bspc rule --add  Viewnior state=floating center=on
bspc rule --add  Zathura state=fullscreen center=on
bspc rule --add  file-roller state=floating center=on
bspc rule --add  floaterm state=floating center=on
bspc rule --add  Spotify state=pseudo_tiled
bspc rule --add  transmission-gtk state=pseudo_tiled
bspc rule --add  astime sticky=on
bspc rule --add  yad state=floating
bspc rule --add  Docky layer=above border=off manage=on
bspc rule --add  Plank layer=above border=off manage=on
bspc rule --add  wbar layer=above
bspc rule --add  dockbarx layer=above
bspc rule --add  gnome-pie border=off manage=off
bspc rule --add  wpa_gui state=pseudo_tiled
bspc rule --add  libreoffice state=tiled
bspc rule --add  '*:libreofficedev' state=tiled
bspc rule --add  '*:soffice' state=tiled
bspc rule --add  9menu border=off manage=off
bspc rule --add  tint2 border=off manage=off
bspc rule --add  Display state=floating layer=above border=off private=on manage=on
bspc rule --add  Conky state=floating border=off layer=below sticky=on manage=off locked=on

###Launch conky
sleep 3
conky -d 

###Fix bspwm not managing properly the xfce4-panel
xdotool search --onlyvisible --class xfce4-panel behave %@ mouse-enter windowraise &

###Launch desknamer
desknamer &
